rm(list = ls())
gc()

library(magrittr)
library(tidyverse)
library(data.table)
library(lubridate)
library(dtplyr)
library(zoo)
library(slider)

library(terra)
library(raster)
library(sf)
library(exactextractr)
sf_use_s2(FALSE)

library(tidymodels)
library(fixest)
library(Matrix)
library(matrixStats)
library(ncdf4)
library(mgcv)
library(forecast)
library(splines)
library(collapse)
library(furrr)
library(correlation)

library(ggplot2)
library(ggrepel)
library(ggside)
library(ggdensity)
library(ggupset)
library(ggpointdensity)
library(ggpmisc)
library(gghighlight)
library(ggdist)
library(ggstar)
library(ggh4x)
library(biscale)
library(viridis)
library(cowplot)
library(hrbrthemes)
library(patchwork)
library(openair)
library(latex2exp)
library(scales)

if (Sys.info()[1] == "Windows") {
  sysfonts::font_add("Roboto Condensed", "C:/Program Files/R/R-4.2.3/library/roboto-condensed/RobotoCondensed-Regular.ttf")
}
showtext::showtext_auto()
